---
name: 'Setup full PHP Environment'
description: 'Sets up the PHP environment for the project'

runs:
  using: 'composite'
  services:
    mysql:
      image: mysql:8.0
      env:
        MYSQL_DATABASE: testing
        MYSQL_ROOT_PASSWORD: testrootpass
        MYSQL_USER: sail
        MYSQL_PASSWORD: password

      ports:
        - 3306:3306
      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

  steps:
    - name: Setup PHP
      uses: ./.github/actions/setup-php-base
      with:
        add-extensions: mysql, pdo_mysql

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install NPM dependencies
      shell: bash
      run: npm install

    - name: Run Vite build
      shell: bash
      run: npm run build
