---
name: "CI"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pint:
    name: "Code style analysis (pint)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php-base

      - name: Check code style
        run: php ./vendor/bin/pint --test

  larastan:
    name: "Phpstan analysis (larastan)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php-base

      - name: Run Larastan
        run: php ./vendor/bin/phpstan

  tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php-full

      - name: Run tests
        run: php artisan test --coverage
