---
name: "CI"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pint:
    name: "Code style analysis (pint)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php-base

      - name: Check code style
        run: php ./vendor/bin/pint --test

  larastan:
    name: "Phpstan analysis (larastan)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php-base

      - name: Run Larastan
        run: php ./vendor/bin/phpstan

  tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php-full

      - name: Run tests
        run: php artisan test --coverage --coverage-clover=report/clover.xml

      - name: Send coverage monitor on pull request
        if: github.actor != 'dependabot[bot]'
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: report/clover.xml
          threshold_alert: 30
          threshold_warning: 70
